ayudantias/07_bulma/ayudantia/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/delete' => 'devise/registrations#destroy'
  end
  resources :articles
  resources :categories
  resources :meals
  root 'welcome#index'
end

ayudantias/07_bulma/ayudantia/app/models/meal.rb
class Meal < ApplicationRecord
end

ayudantias/07_bulma/ayudantia/app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def create
    @meal = Meal.new(meal_params)
    if @meal.save
      redirect_to @meal
    else
      render 'new'
    end
  end

  def new
    @meal = Meal.new
  end

  def index
    @meals = Meal.all
  end

  def update
    @meal = Meal.find(params[:id])

    if @meal.update(meal_params)
      redirect_to @meal
    else
      render 'edit'
    end
  end

  def destroy
    @meal = Meal.find(params[:id])
    @meal.destroy

    redirect_to meals_path
  end

  def show
    @meal = Meal.find(params[:id])
  end

  private

  def meal_params
    params.require(:meal).permit(:name, :thumb, :mealId)
  end
end

ayudantias/07_bulma/ayudantia/app/helpers/meals_helper.rb
module MealsHelper
end

ayudantias/07_bulma/ayudantia/app/views/meals/index.html.erb
<section class="hero is-fullheight is-link">
  <div class="hero">


<h1 class="title is-1">Listing Meals</h1>
<%= link_to 'Back', :back %>
<a href="/">Home</a>
<div class="columns is-multiline">
  <% @meals.each do |meal| %>
    <div class="column is-one-quarter">
  <div class="card">
    <div class="card-image">
      <figure class="image is-240x240">
        <img src="<%= meal.thumb %>" alt="Placeholder image">
      </figure>
    </div>
    <div class="card-content">
      <div class="media">
        <div class="media-content">
          <p class="title is-4" style="color: black"><em><%= meal.name %></em></p>
        </div>
      </div>
      <%= link_to 'Show', meal_path(meal) %>
      <%= link_to 'Edit', edit_meal_path(meal) %>
      <%= link_to 'Destroy', meal_path(meal),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
    </div>
  <% end %>
</div>
  </div>
</section>

ayudantias/07_bulma/ayudantia/app/views/meals/show.html.erb
<%
  response = RestClient.get "https://www.themealdb.com/api/json/v1/1/lookup.php?i=#{@meal.mealId}"
  json = JSON.parse response
  meal = json['meals'][0]
%>

<p>
  <strong>Name:</strong>
  <%= @meal.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= meal['strCategory'] %>
</p>

<p>
  <strong>Area:</strong>
  <%= meal['strArea'] %>
</p>

<p>
  <strong>Instructions:</strong>
  <%= meal['strInstructions'] %>
</p>

<p>
  <strong>Thumb:</strong>
  <%= @meal.thumb %>
</p>

<img src="<%= @meal.thumb %>" alt="meal picture">

<p>
  <strong>mealId:</strong>
  <%= @meal.mealId %>
</p>

<p>
  <strong>Ingredients</strong>
</p>

<ul>
  <% 20.times do |i| %>
    <% if meal["strIngredient#{i+1}"] != '' %>
    <li><%= meal["strIngredient#{i+1}"] %></li>
    <% end %>
  <% end %>
</ul>
<%= link_to 'Back', meals_path %>