ayudantias/07_bulma/ayudantia/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/delete' => 'devise/registrations#destroy'
  end
  resources :articles
  resources :categories
  resources :meals
  root 'welcome#index'
end

ayudantias/07_bulma/ayudantia/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @articles = Article.all
    @meals = Meal.all
    @categories = Category.all
  end

  def meal
    response = RestClient.get 'https://www.themealdb.com/api/json/v1/1/random.php'
    json = JSON.parse response
    puts json
    # if !json.nil?
    #   json['data'].map do |meal|
    #     Meal.create()
    #   end
    # else
    #   puts 'error seeding meals'
    # end
  end

  def meal_cat
    response = RestClient.get 'https://www.themealdb.com/api/json/v1/1/categories.php'
    json = JSON.parse response
    categories = json['categories']
    render
  end
end

ayudantias/07_bulma/ayudantia/app/helpers/welcome_helper.rb
module WelcomeHelper
end

ayudantias/07_bulma/ayudantia/app/views/welcome/index.html.erb
<%#
<!--  meals = []-->
<!--  1.times do |i|-->
<!--    response = RestClient.get 'https://www.themealdb.com/api/json/v1/1/random.php'-->
<!--    json = JSON.parse response-->
<!--    meal = json['meals'][0]-->
<!--    puts meal['idMeal']-->
<!--  end-->
%>
<% if user_signed_in? %>
  <h1>Bienvendo a DCComidas</h1>
  <p><%= current_user.email %></p>
  <p>Cantidad de comidas en la app: <%= @meals.length %></p>
  <p>Cantidad de categorias en la app: <%= @categories.length %></p>

  <%= link_to 'Ver Categorias', categories_path %>
  <%= link_to 'Ver Comidas', meals_path %>

  <%= link_to 'Desconectarse', destroy_user_session_path %>

<% else %>
  <h1>Welcome</h1>
  <p>No estas registrado</p>


  <%= link_to 'Registrarse', new_user_registration_path %>

  <%= link_to 'Conectarse', new_user_session_path %>

<% end %>