ayudantias/07_bulma/ayudantia/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/delete' => 'devise/registrations#destroy'
  end
  resources :articles
  resources :categories
  resources :meals
  root 'welcome#index'
end

ayudantias/07_bulma/ayudantia/app/models/category.rb
class Category < ApplicationRecord
end

ayudantias/07_bulma/ayudantia/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end

  def new
    @category = Category.new
  end

  def index
    @categories = Category.all
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to @category
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path
  end

  def show
    @category = Category.find(params[:id])
  end

  private

  def category_params
    params.require(:category).permit(:name, :description, :thumb)
  end
end

ayudantias/07_bulma/ayudantia/app/helpers/categories_helper.rb
module CategoriesHelper
end

ayudantias/07_bulma/ayudantia/app/views/categories/_form.html.erb
<%= form_with model: @category, local: true do |form| %>

  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@category.errors.count, "error") %> prohibited
        this category from being saved:
      </h2>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :thumb %><br>
    <%= form.text_field :thumb %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

ayudantias/07_bulma/ayudantia/app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

ayudantias/07_bulma/ayudantia/app/views/categories/index.html.erb
<%= stylesheet_link_tag 'categoria.css' %>
<h1>Listing Categories</h1>
<%= link_to 'Back', :back %>
<a href="/">Home</a>
<table>
  <tr>
    <th>Name</th>
    <th>Thumb</th>
    <th>Description</th>
    <th colspan="3"></th>
  </tr>

  <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td><%= category.thumb %></td>
      <td><%= category.description %></td>
      <td><%= link_to 'Show', category_path(category) %></td>
      <td><%= link_to 'Edit', edit_category_path(category) %></td>
      <td><%= link_to 'Destroy', category_path(category),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

ayudantias/07_bulma/ayudantia/app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

ayudantias/07_bulma/ayudantia/app/views/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Thumb:</strong>
  <%= @category.thumb %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Back', categories_path %>